Feat/add route teacher
IC-TestIt/Back-End pull request #15
Opened 2017-07-15 04:34 UTC by medson10

2017-07-15 04:35 UTC, medson10 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rota - Cadastro Professor](https://trello.com/c/1MNmrPwl/52-rota-cadastro-professor)

2017-07-15 04:36 UTC, medson10 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rota - Buscar Informações Usuario](https://trello.com/c/8iEy52lL/57-rota-buscar-informa%C3%A7%C3%B5es-usuario)

2017-07-15 04:47 UTC, Vitormdias requested changes

2017-07-15 04:47 UTC, Vitormdias commented on TestIt.API/Controllers/UserController.cs
> +            User user = Mapper.Map<User>(viewModel);
Primeiro Salvar o usuário e depois criar professor

2017-07-15 04:47 UTC, Vitormdias commented on TestIt.API/Controllers/UserController.cs
> +            {
Update do professor desnecessário

2017-07-15 04:47 UTC, Vitormdias commented on TestIt.API/Controllers/UserController.cs
> +            }
Delete User?

2017-07-15 04:47 UTC, Vitormdias commented on TestIt.Business/Services/TeacherService.cs
> +            return teacherRepository.GetSingle(t => t.User.Id == id);
Campo UserId

2017-07-16 20:55 UTC, medson10 commented
Metodo delete corrigido

2017-07-17 02:43 UTC, merged