Imp/get teacher tests
IC-TestIt/Back-End pull request #87
Opened 2017-10-06 00:03 UTC by LuizGuilhermeSoares

2017-10-06 12:07 UTC, Vitormdias requested changes

2017-10-06 12:07 UTC, Vitormdias commented on TestIt.Data/Repositories/TestRepository.cs
> +        {
Refatorar, muitas idas ao banco

2017-10-06 12:07 UTC, Vitormdias commented on TestIt.Model/Enums.cs
> +        notApplied = 4
Primeira maiuscula

2017-10-10 01:07 UTC, Vitormdias commented
@LuizGuilhermeSoares @medson10  atualizei aqui, agora estou retornando uma lista de class tests, assim nós temos todas as provas que ele aplicou por status, só que na mesmo lista, otimizei as idas ao banco, e mudei a view model para trazer informações que eu acho que são convenientes

2017-10-10 01:08 UTC, Vitormdias commented
![](https://github.trello.services/images/mini-trello-icon.png) [Alterar rota minhas provas(professor)](https://trello.com/c/TMu2HpMi/220-alterar-rota-minhas-provasprofessor)

2017-10-10 05:35 UTC, medson10 commented
Observei um grave problema, e se é uma prova q nunca foi aplicada ? Ela não aparece, no meu teste antes aparecia 19 tests pro meu user, agr aparecem 6

2017-10-10 05:42 UTC, medson10 requested changes
Ta retornando só os tests q tem algum class test

2017-10-10 12:23 UTC, Vitormdias approved these changes

2017-10-10 12:36 UTC, Vitormdias commented
To vendo aqui, achei o problema

2017-10-10 12:39 UTC, Vitormdias commented
Mas vou fazer o seguinte vou trazer todas as provas como não aplicadas e as outras, pq tipo do jeito que a gente fez, se o professor quiser aplicar a mesma prova pra duas turmas não vai aparecer o status que deixa ele aplicar, então tipo o certo é só não trazer ela pro professor se ele não tiver aplicado ela pra todas turmas

2017-10-10 14:09 UTC, Vitormdias commented
Vou ter que acrescentar a regra que uma prova pode ser aplicada pra uma turma apenas uma vez

2017-10-10 14:28 UTC, Vitormdias commented
### Status
Não Aplicada - 1
Em Andamento - 2
Não Corrigida - 3
Corrigida - 4

2017-10-10 14:49 UTC, medson10 commented
Blz

2017-10-11 02:14 UTC, merged